version : "3.8"

services:

  mysql_db:
    image: mysql:8.0.29
    environment:
      - MYSQL_DATABASE=mediatime-db
      - MYSQL_ROOT_PASSWORD=Paulezeh123
    volumes:
      - "./DB/DatabaseScripts/CreateDatabase.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./DB/DatabaseScripts/Automation/Seeding.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - 6603:3306

  app: 
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1000:3000
      - 2000:3000
      - 3000:3000
      - 4000:3000
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
    depends_on:
      - mysql_db
    restart: unless-stopped
  
  nginx:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - app
    restart: unless-stopped
    



    
