version : "3.8"

services:

  mysql_db:
    image: mysql:8.0.29
    environment:
      - MYSQL_DATABASE=mediatime-db
      - MYSQL_ROOT_PASSWORD=Paulezeh123
    volumes:
      - "./DB/DatabaseScripts/CreateDatabase.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./DB/DatabaseScripts/Automation/Seeding.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - 6603:3306

  app: 
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    scale: 4
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
    depends_on:
      - mysql_db
    restart: unless-stopped
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    restart: unless-stopped

    
